# Generated by Django 6.0.1 on 2026-02-01 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comensales', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comensales',
            options={'verbose_name': 'Comensal', 'verbose_name_plural': 'Comensales'},
        ),
        migrations.RemoveField(
            model_name='comensales',
            name='DNI',
        ),
        migrations.RemoveField(
            model_name='comensales',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='comensales',
            name='nombre',
        ),
    ]
