# Generated by Django 6.0.1 on 2026-02-01 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comensales', '0002_alter_comensales_options_remove_comensales_dni_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comensales',
            name='DNI',
            field=models.CharField(default='00000000', max_length=200),
        ),
        migrations.AddField(
            model_name='comensales',
            name='apellido',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comensales',
            name='nombre',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
