# Generated by Django 6.0.1 on 2026-02-01 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comensales', '0003_comensales_dni_comensales_apellido_comensales_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comensales',
            name='apellido',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
