# Generated by Django 6.0.1 on 2026-02-01 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('platos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='platos',
            options={'verbose_name': 'Plato', 'verbose_name_plural': 'Platos'},
        ),
        migrations.RemoveField(
            model_name='platos',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='platos',
            name='precio',
        ),
    ]
