# Generated by Django 6.0.1 on 2026-02-01 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platos', '0002_alter_platos_options_remove_platos_nombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='platos',
            name='nombre',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='platos',
            name='precio',
            field=models.IntegerField(default=0),
        ),
    ]
