# Generated by Django 6.0.1 on 2026-02-01 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meseros', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pedido',
            new_name='Meseros',
        ),
    ]
