# Generated by Django 6.0.1 on 2026-02-01 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meseros', '0002_rename_pedido_meseros'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meseros',
            options={'verbose_name': 'Mesero', 'verbose_name_plural': 'Meseros'},
        ),
        migrations.RemoveField(
            model_name='meseros',
            name='edad',
        ),
        migrations.RemoveField(
            model_name='meseros',
            name='nacionalidad',
        ),
        migrations.RemoveField(
            model_name='meseros',
            name='nombre',
        ),
    ]
