# Generated by Django 6.0.1 on 2026-02-01 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meseros', '0003_alter_meseros_options_remove_meseros_edad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meseros',
            name='edad',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='meseros',
            name='nacionalidad',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='meseros',
            name='nombre',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
