# Generated by Django 6.0.1 on 2026-02-01 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comensales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('comensales', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comensales.comensales')),
            ],
        ),
    ]
